
#Stage 1 (The first stage builds the JAR file, and the second stage uses a smaller base image to run the application)
# Use the Maven image to build the application
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app
COPY . /app
RUN mvn clean package -DskipTests


#Stage 2 (copies the JAR from the build stage to the runtime stage)
# Use a smaller image to run the application
FROM openjdk:17-jdk-slim
ARG JAR_FILE=target/springboot-docker-compose-0.0.1-SNAPSHOT.jar
COPY --from=build /app/${JAR_FILE} /springboot-docker-compose.jar
ENTRYPOINT ["java", "-jar", "/springboot-docker-compose.jar"]
